import "@/app/globals.css";
import type { Metadata } from "next";
import { Archivo, Inter } from "next/font/google";
import MouseCursorComponent from "@/app/components/MouseCursorComponent";
import { SessionProvider } from "next-auth/react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
const archivo = Archivo({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-archivo",
});

const inter = Inter({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${archivo.variable} ${inter.variable} font-inter antialiased`}
        suppressHydrationWarning
      >
        <SessionProvider>
          <ToastContainer position="bottom-right" hideProgressBar className={"z-50"} />
          <MouseCursorComponent>{children}</MouseCursorComponent>
        </SessionProvider>
      </body>
    </html>
  );
}
